refactor(scripts): improve robustness and error handling

diff --git a/local/bin/ex b/local/bin/ex
--- a/local/bin/ex
+++ b/local/bin/ex
@@ -1,26 +1,22 @@
 #!/bin/bash
 
-declare FORMAT_ERROR="\e[1;31m[ERROR]"
-declare FORMAT_TITLE="\e[1;34m"
-declare FORMAT_RESET="\e[0m"
-
-function help() {
-	printf "%bUSAGE:%b $(basename "$0") INPUT_FILE\n" "$FORMAT_TITLE" "$FORMAT_RESET"
-	exit 1
-}
-
+declare -r FORMAT_SUCCESS="\e[1;32m[SUCCESS]\e[0m"
+declare -r FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"
 
 function main() {
-	local file="$1"
-
 	while getopts "h" opt; do
 		case $opt in
-			h) help ;;
-			*) exit 1 ;;
+			h) printf "\e[1;34mUSAGE:\e[0m %s INPUT_FILE\n" "$(basename "$0")" && exit 0 ;;
+			*) printf "%b Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1 ;;
 		esac
 	done
 
-	[ -z "$file" ] && help
+	shift $((OPTIND - 1))
+
+	local file="$1"
+
+	[[ -z "$file" ]] && printf "%b No input file provided. Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1
+	[[ ! -f "$file" ]] && printf "%b File '%s' does not exist.\n" "$FORMAT_ERROR" "$file" >&2 && exit 1
 
 	case "$file" in
 		*.tar.bz2) xjf        "$file" ;;
@@ -37,8 +33,12 @@ function main() {
 		*.deb)     ar x       "$file" ;;
 		*.tar.xz)  tar xf     "$file" ;;
 		*.tar.zst) unzstd     "$file" ;;
-		*) printf "%b $file cannot be extracted via ex() %b\n" "$FORMAT_ERROR" "$FORMAT_RESET" ;;
+		*) printf "%b $file cannot be extracted via ex().\n" "$FORMAT_ERROR" >&2 && exit 1 ;;
 	esac
+
+	printf "%b %s extracted successfully.\n" "$FORMAT_SUCCESS" "$file"
+
+	return 0
 }
 
 main "$@"
diff --git a/local/bin/gfix b/local/bin/gfix
--- a/local/bin/gfix
+++ b/local/bin/gfix
@@ -1,11 +1,31 @@
 #!/bin/bash
 
+declare -r FORMAT_SUCCESS="\e[1;32m[SUCCESS]\e[0m"
+declare -r FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"
+
 function main() {
-	printf "The commit: "
+	if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+		printf "%b Not a git repository.\n" "$FORMAT_ERROR"
+		exit 1
+	fi
+
+	if ! git rev-parse HEAD~1 >/dev/null 2>&1; then
+		printf "%b Not enough commits to perform a reset.\n" "$FORMAT_ERROR"
+		exit 1
+	fi
+
+	printf "Current commit:\n"
 	git log --oneline --graph --decorate -n 1
-	git reset --soft HEAD~1
-	printf "\nWas restarted to previous commit: "
-	git log --oneline --graph --decorate -n 1
+
+	if git reset --soft HEAD~1; then
+		printf "\n%b Reverted to previous commit:\n" "$FORMAT_SUCCESS"
+		git log --oneline --graph --decorate -n 1
+	else
+		printf "\n%b Failed to perform git reset.\n" "$FORMAT_ERROR"
+		exit 1
+	fi
+
+	return 0
 }
 
 main "$@"
diff --git a/local/bin/hdmi b/local/bin/hdmi
--- a/local/bin/hdmi
+++ b/local/bin/hdmi
@@ -1,14 +1,7 @@
 #!/bin/bash
 
-declare FORMAT_TITLE="\e[1;34m"
-declare FORMAT_WARNING="\e[1;33m[WARNING]"
-declare FORMAT_RESET="\e[0m"
-
-function help() {
-	printf "%bUSAGE:%b $(basename "$0") {connect|disconnect}\n" "$FORMAT_TITLE" "$FORMAT_RESET"
-	exit 1
-}
-
+declare -r FORMAT_SUCCESS="\e[1;32m[SUCCESS]\e[0m"
+declare -r FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"
 
 function connect() {
 	printf "Select resolution:\n"
@@ -18,41 +11,62 @@ function connect() {
 	printf "Enter your choice [1-3]: "
 	read -r ans
 
-	local resolution="1330x768"
+	local resolution=""
 	case $ans in
 		1) resolution="1330x768" ;;
 		2) resolution="1600x900" ;;
 		3) resolution="1920x1080" ;;
-		*) printf "%b Invalid choice: '%s'%b\n" "$FORMAT_WARNING" "$ans" "$FORMAT_RESET";;
+		*) printf "%b Invalid choice: '%s'.\n" "$FORMAT_ERROR" "$ans" >&2 && exit 1 ;;
 	esac
 
-	printf "Setting HDMI resolution to %s %b\n" "$resolution" "$FORMAT_RESET"
+	printf "Setting HDMI resolution to %s.\n" "$resolution"
 
-	xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode $resolution --rate 60 --rotate normal --right-of eDP-1
-	bspc wm -r
+	xrandr --output eDP-1 --auto --primary  --output HDMI-1 --mode $resolution --right-of eDP-1
+
+	if [[ $? -ne 0 ]]; then
+		printf "%b Failed to connect HDMI.\n" "$FORMAT_ERROR" >&2
+		return 1
+	fi
+
+	return 0
 }
 
 
 function disconnect() {
 	xrandr --output HDMI-1 --off
-	bspc wm -r
+
+	if [[ $? -ne 0 ]]; then
+		printf "%b Failed to disconnect HDMI.\n" "$FORMAT_ERROR" >&2
+		return 1
+	fi
+	printf "%b HDMI disconnected successfully.\n" "$FORMAT_SUCCESS"
+
+	return 0
 }
 
 
 function main() {
-	if [[ $# -eq 0 ]]; then
-		help
-	fi
+	while getopts "h" opt; do
+		case $opt in
+			h) printf "\e[1;34mUSAGE:\e[0m %s {connect|disconnect}\n" "$(basename "$0")" && exit 0 ;;
+			*) printf "%b Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1 ;;
+		esac
+	done
 
-	option=$1
+	local option="$1"
+	[[ -z "$option" ]] && printf "%b No option provided. Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1
 
 	if [[ $option == "connect" ]]; then
 		connect
 	elif [[ $option == "disconnect" ]]; then
 		disconnect
 	else
-		help
+		printf "%b Invalid option: '%s'. Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$option" "$(basename "$0")" >&2 && exit 1
 	fi
+
+	bspc wm -r
+
+	return 0
 }
 
 main "$@"
diff --git a/local/bin/mdtopdf b/local/bin/mdtopdf
--- a/local/bin/mdtopdf
+++ b/local/bin/mdtopdf
@@ -1,13 +1,7 @@
 #!/bin/bash
 
-declare FORMAT_SUCCESS="\e[1;32m[SUCCESS]\e[0m"
-declare FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"
-
-function help() {
-	echo -e "\e[1;34mUSAGE:\e[0m $(basename "$0") <file.md>"
-	exit 0
-}
-
+declare -r FORMAT_SUCCESS="\e[1;32m[SUCCESS]\e[0m"
+declare -r FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"
 
 function createLuaFilter() {
 	local filterFile="$1"
@@ -95,7 +89,12 @@ EOF
 
 
 function main() {
-	[ -z "$1" ] || [ "$1" == "-h" ] && help
+	while getopts "h" opt; do
+		case $opt in
+			h) printf "\e[1;34mUSAGE:\e[0m %s FILE_NAME\n" "$(basename "$0")" && exit 0 ;;
+			*) printf "%b Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1 ;;
+		esac
+	done
 
     local inputFile="$1"
     local filename="${inputFile%.*}"
@@ -138,11 +137,11 @@ function main() {
 		-V header-includes="\definecolor{drx-color-default}{HTML}{6C664B}"; then
 
 		printf "%b PDF generated: «%s»\n" "$FORMAT_SUCCESS" "$outputFile"
-		exit 0
+		return 0
 	fi
 
 	printf "%b Compilation failed for file: «%s»\n" "$FORMAT_ERROR" "$inputFile"
-	exit 1
+	return 1
 }
 
 main "$@"
