feat(scripts): add 'grun' flag support:
- Implemented getopts to handle -f for extra flags
- Added -h flag for usage and help information
- Refactored argument shift logic for better parsing

diff --git a/local/bin/grun b/local/bin/grun
--- a/local/bin/grun
+++ b/local/bin/grun
@@ -1,28 +1,37 @@
 #!/bin/bash
 
-declare FORMAT_TITLE="\e[1;34m"
-declare FORMAT_RESET="\e[0m"
-
-function help() {
-	printf "%bUSAGE:%b $(basename "$0") [OPTIONS] INPUT_FILE\n" "$FORMAT_TITLE" "$FORMAT_RESET"
-	exit 1
-}
+declare -r FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"
 
 function main() {
-	fileExtension=${1##*.}
+	while getopts "hf:" opt; do
+		case $opt in
+			h) printf "\e[1;34mUSAGE:\e[0m %s [-f \"FLAGS\"] INPUT_FILE\n" "$(basename "$0")" && exit 0 ;;
+			f) extraFlags="$OPTARG" ;;
+			*) printf "%b Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1 ;;
+		esac
+	done
 
-	if [[ $# -eq 0 || ! $fileExtension =~ ^(cpp|c)$ ]]; then
-		help
+	shift $((OPTIND -1))
+
+	local file="$1"
+
+	[[ -z "$file" ]] && printf "%b No input file provided. Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1
+	[[ ! -f "$file" ]] && printf "%b File '%s' does not exist.\n" "$FORMAT_ERROR" "$file" >&2 && exit 1
+
+	local fileExtension=${file##*.}
+	local output=$(basename "$file" ".$fileExtension")
+	if [[ "$fileExtension" == "cpp" ]]; then
+		g++ "$file" -o "${output}.out" -Wall $extraFlags "${@:2}" && ./"${output}.out"
+	elif [[ "$fileExtension" == "c" ]]; then
+		gcc "$file" -o "${output}.out" -Wall $extraFlags "${@:2}" && ./"${output}.out"
+	else
+		printf "%b File '%s' is not a C or C++ source file.\n" "$FORMAT_ERROR" "$file" >&2
+		exit 1
 	fi
 
-	if [[ ${1##*.} == "cpp" ]]; then
-		filename=$(basename "$1" .cpp)
-		g++ "$1" -o "${filename}.out" -Wall "${@:2}" && ./"${filename}.out"
-	elif [[ ${1##*.} == "c" ]]; then
-		filename=$(basename "$1" .c)
-		gcc "$1" -o "${filename}.out" -Wall "${@:2}" && ./"${filename}.out"
-	fi
-	rm "${filename}.out"
+	rm "${output}.out"
+
+	return 0
 }
 
 main "$@"
