feat(scripts): add 'lofi' multi-source support and options

diff --git a/local/bin/lofi b/local/bin/lofi
--- a/local/bin/lofi
+++ b/local/bin/lofi
@@ -1,37 +1,71 @@
 #!/bin/bash
 
-declare FORMAT_TITLE="\e[1;34m"
-declare FORMAT_RESET="\e[0m"
+declare -r FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"
+declare -r COVER_PATH="$HOME/.local/share/lofi.jpg"
 
-declare COVER_PATH="$HOME/.local/share/lofi"
+declare -a SOURCES=(
+	"http://youtu.be/jfKfPfyJRdk"
+	"http://youtu.be/HuFYqnbVbzY"
+	"http://youtu.be/28KRPhVzCus"
+	"http://youtu.be/-OekvEFm1lo"
+	"http://youtu.be/4xDzrJKXOOY"
+)
 
 function help() {
-	printf "%bUSAGE:%b $(basename "$0") VOLUME\n" "$FORMAT_TITLE" "$FORMAT_RESET"
-	exit 1
+	declare -r FORMAT_BOLD="\e[1;34m"
+	declare -r FORMAT_RESET="\e[0m"
+	echo -e "${FORMAT_BOLD}USAGE:${FORMAT_RESET} $(basename "$0") [OPTIONS] [VOLUME]
+
+${FORMAT_BOLD}DESCRIPTION:${FORMAT_RESET}
+    Streams random Lofi music from YouTube and visualizes it using cava.
+
+${FORMAT_BOLD}ARGUMENTS:${FORMAT_RESET}
+    VOLUME         Set the initial volume (0-100). Default: 50.
+
+${FORMAT_BOLD}OPTIONS:${FORMAT_RESET}
+    -d             Debug mode: Run in foreground and show output.
+    -s SOURCE      Specify a custom YouTube URL to stream."
+
+	return 0
 }
 
 
 function main() {
-	[[ $1 == "-h" ]] && help
+	local isDebug=false
+	local source="${SOURCES[$RANDOM % ${#SOURCES[@]}]}"
 
-	local volume="0.5"
-	if [[ -n $1 ]]; then
-		volume=$(echo "scale=2; $1 / 100" | bc)
+	while getopts "hds:" opt; do
+		case $opt in
+			h) help && exit 0 ;;
+			d) isDebug=true ;;
+			s) source="$OPTARG" ;;
+			*) printf "%b Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1 ;;
+		esac
+	done
+
+	shift $((OPTIND - 1))
+
+	if [[ ! -f "$COVER_PATH" ]]; then
+		wget --output-document "$COVER_PATH" "https://f4.bcbits.com/img/a0591684555_10.jpg"
 	fi
 
-	if [[ ! -d "$COVER_PATH" ]]; then
-		mkdir "$COVER_PATH"
-		wget --output-document "$COVER_PATH/lofi.jpg" "https://f4.bcbits.com/img/a0591684555_10.jpg"
+	local volume=$(echo "scale=2; ${1:-50} / 100" | bc)
+	cp -f "$COVER_PATH" "/tmp/thumbnail.jpg"
+
+	if $isDebug; then
+		yt-dlp --format "ba/w" -o - "$source" | ffplay -nodisp -af "volume=$volume" -
+		exit 0
 	fi
 
 	(
-		yt-dlp --format "w*" -o - 'https://www.youtube.com/watch?v=jfKfPfyJRdk' | ffplay -nodisp -af "volume=$volume" -
+		yt-dlp --format "ba/w" -o - "$source" | ffplay -nodisp -af "volume=$volume" -
 	) > /dev/null 2>&1 &
+    local PGID=$(ps -o pgid= -p $! | tr -d ' ')
 
-	cp -f "$HOME/.local/share/lofi/lofi.jpg" "/tmp/thumbnail.jpg"
-    PGID=$(ps -o pgid= -p $! | tr -d ' ')
 	cava
-    kill -TERM -$PGID:
+    kill -TERM -"$PGID"
+
+	return 0
 }
 
 main "$@"
