feat(bash): the scripts have been updated to the latest version.

diff --git a/scripts/opdoc b/scripts/opdoc
--- a/scripts/opdoc
+++ b/scripts/opdoc
@@ -6,43 +6,43 @@ END="\e[0m"
 documentLocation=~/Documents/Obsidian/Workspace/Cheatsheets/
 
 function errorMessage() {
-    echo -e "$ERROR ► the file you are trying to access does not exist$END"
-    exit 0
+	echo -e "$ERROR ► the file you are trying to access does not exist$END"
+	exit 0
 }
 
 
 function todo() {
-    todoLocation="$documentLocation/todo.md"
+	todoLocation="$documentLocation/todo.md"
 
-    if [ -f "$todoLocation" ]; then
-        nvim $todoLocation
-    else
-        echo "Todo file does not exist. Making it..."
-        touch $todoLocation
-        nvim $todoLocation
-    fi
+	if [ -f "$todoLocation" ]; then
+		nvim $todoLocation
+	else
+		echo "Todo file does not exist. Making it..."
+		touch $todoLocation
+		nvim $todoLocation
+	fi
 }
 
 
 function main() {
-    if [ -z "$1" ]; then
-        errorMessage
-        exit 1
-    fi
+	if [ -z "$1" ]; then
+		errorMessage
+		exit 1
+	fi
 
-    file=$1
+	file=$1
 
-    if [ "$file" == "todo.md" ] || [ "$file" == "todo" ]; then
-        todo
-        exit 0
-    fi
+	if [ "$file" == "todo.md" ] || [ "$file" == "todo" ]; then
+		todo
+		exit 0
+	fi
 
-    if [ -f "$documentLocation$file" ]; then
-        nvim "$documentLocation$file"
-        exit 0
-    fi
+	if [ -f "$documentLocation$file" ]; then
+		nvim "$documentLocation$file"
+		exit 0
+	fi
 
-    errorMessage
+	errorMessage
 }
 
 main $@
diff --git a/scripts/touches b/scripts/touches
--- a/scripts/touches
+++ b/scripts/touches
@@ -4,43 +4,43 @@ FILES="\e[0;32m"
 END="\e[0m"
 
 function help() {
-    echo
-    echo "USAGE: touches [FILES NAME] [FILES QUANTITY] [FILES ROUTE]"
-    echo
-    echo "DESCRIPTION: Creates a default file in a specific programming language."
-    echo
-    echo "ARGUMENTS:"
-    echo "  FILE TYPE: bash, c++, python, rust."
-    echo "  FILE NAME: (Optional) The name of the file."
-    echo
-    echo "EXAMPLES:"
-    echo "  defaultfi c++ helloWorld"
-    echo "  defaultfi python"
-    echo
-    echo "Report bugs to https://github.com/druxorey/pybash-scripts/issues"
-    echo
-    exit 1
+	echo
+	echo "USAGE: touches [FILES NAME] [FILES QUANTITY] [FILES ROUTE]"
+	echo
+	echo "DESCRIPTION: Creates a default file in a specific programming language."
+	echo
+	echo "ARGUMENTS:"
+	echo "  FILE TYPE: bash, c++, python, rust."
+	echo "  FILE NAME: (Optional) The name of the file."
+	echo
+	echo "EXAMPLES:"
+	echo "  defaultfi c++ helloWorld"
+	echo "  defaultfi python"
+	echo
+	echo "Report bugs to https://github.com/druxorey/pybash-scripts/issues"
+	echo
+	exit 1
 }
 
 function main () {
 
-    [ $# -lt 2 ] && help
-    [ $2 -lt 1 ] && error "Error: el numero de ficheros no puede ser menor que 1"
+	[ $# -lt 2 ] && help
+	[ $2 -lt 1 ] && error "Error: el numero de ficheros no puede ser menor que 1"
 
-    route=${3:-$(pwd)}
+	route=${3:-$(pwd)}
 
-    name=$(echo $1 | rev | cut -d'.' -f2- | rev)
-    extension=$(echo $1 | rev | cut -d'.' -f1 | rev)
+	name=$(echo $1 | rev | cut -d'.' -f2- | rev)
+	extension=$(echo $1 | rev | cut -d'.' -f1 | rev)
 
-    for (( i = 1; i <= $2; i++ )); do
-        if [ $i -gt 9 ]; then
-            file="$name-$i.$extension"
-        else
-            file="$name-0$i.$extension"
-        fi
-        touch "$route/$file"
-        echo -e "Fichero $FILES$file$END creado" | tr -s /
-    done
+	for (( i = 1; i <= $2; i++ )); do
+		if [ $i -gt 9 ]; then
+			file="$name-$i.$extension"
+		else
+			file="$name-0$i.$extension"
+		fi
+		touch "$route/$file"
+		echo -e "Fichero $FILES$file$END creado" | tr -s /
+	done
 }
 
 main $@
